name: Build and Release

on:
  push:
    tags:
      - 'v*'  # triggers only on tags like v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: linux
            os: ubuntu-latest
            out: shamir_linux
            exe: shamir_linux
          - target: windows
            os: windows-latest
            out: shamir_windows
            exe: shamir_windows.exe
          - target: macos
            os: macos-latest
            out: shamir_macos
            exe: shamir_macos

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Get deps in plugin root
        run: flutter pub get

      - name: Get deps in secretsplit-safeguard
        run: flutter pub get
        working-directory: secretsplit-safeguard

      - name: Create output dir
        run: mkdir -p ../build
        working-directory: secretsplit-safeguard

      - name: Compile executable
        run: dart compile exe bin/main.dart -o ../build/${{ matrix.exe }}
        working-directory: secretsplit-safeguard

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out }}
          path: build/${{ matrix.exe }}

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/shamir_linux/shamir_linux
            dist/shamir_windows/shamir_windows.exe
            dist/shamir_macos/shamir_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
