name: Build and Release

on:
  push:
    tags:
      - 'v*'  # triggers only on tags like v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # or whatever version you want
      - run: pwd && ls -R

      - name: Get deps in plugin root
        run: flutter pub get

      - name: Get deps in secretsplit-safeguard
        run: flutter pub get
        working-directory: secretsplit-safeguard

      - name: Create output dir
        run: mkdir -p ../build
        working-directory: secretsplit-safeguard

      - name: Compile executable
        run: dart compile exe bin/main.dart -o ../build/shamir_linux
        working-directory: secretsplit-safeguard

      - uses: actions/upload-artifact@v4
        with:
          name: shamir_linux
          path: build/shamir_linux

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # or whatever version you want
      - run: pwd && ls -R

      - name: Get deps in plugin root
        run: flutter pub get

      - name: Get deps in secretsplit-safeguard
        run: flutter pub get
        working-directory: secretsplit-safeguard

      - name: Create output dir
        run: mkdir -p ../build
        working-directory: secretsplit-safeguard

      - name: Compile executable
        run: dart compile exe bin/main.dart -o ../build/shamir_window.exe
        working-directory: secretsplit-safeguard

      - uses: actions/upload-artifact@v4
        with:
          name: shamir_linux
          path: build/shamir_linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # or whatever version you want
      - run: pwd && ls -R

      - name: Get deps in plugin root
        run: flutter pub get

      - name: Get deps in secretsplit-safeguard
        run: flutter pub get
        working-directory: secretsplit-safeguard

      - name: Create output dir
        run: mkdir -p ../build
        working-directory: secretsplit-safeguard

      - name: Compile executable
        run: dart compile exe bin/main.dart -o ../build/shamir_macos
        working-directory: secretsplit-safeguard

      - uses: actions/upload-artifact@v4
        with:
          name: shamir_linux
          path: build/shamir_linux

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/shamir_linux/shamir_linux
            dist/shamir_windows/shamir_windows.exe
            dist/shamir_macos/shamir_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
